import { ref } from 'vue';
import { Icon } from '@iconify/vue';
const img = `<${Icon} icon="material-symbols:more-vert" width="16" height="16" style="color: #539cea" />`;
export const dataSource = ref([
  {
    id: 1,
    name: '太白',
    phone: '123456789',
    waiter: '红日初升,其道大光',
    intention: '仰天大笑出门去,我辈岂是蓬蒿人',
    customerCognitiveApproach: '开元',
    lastContactTime: '2024-10-1',
    dateNextFollowup: '2024-10-1',
    createTime: '2024-10-1',
    status: 1,
    operation: img,
  },
  {
    id: 2,
    name: '子美',
    phone: '123456789',
    waiter: '朱门酒肉臭,路有冻死骨',
    intention: '五更鼓角声悲壮，三峡星河影动摇',
    customerCognitiveApproach: '开元',
    lastContactTime: '2024-10-1',
    dateNextFollowup: '2024-10-1',
    createTime: '2024-10-1',
    status: 1,
    operation: ':',
  },
  {
    id: 3,
    name: '重光',
    phone: '123456789',
    waiter: '黑云压城城欲摧,甲光向日金鳞开',
    intention: '问君能有几多愁？恰似一江春水向东流',
    customerCognitiveApproach: '开宝',
    lastContactTime: '2024-10-1',
    dateNextFollowup: '2024-10-1',
    createTime: '2024-10-1',
    status: 1,
    operation: ':',
  },
  {
    id: 4,
    name: '润之',
    phone: '123456789',
    waiter: '数风流人物,还看今朝',
    intention: '为有牺牲多壮志，敢教日月换新天',
    customerCognitiveApproach: '近代',
    lastContactTime: '2024-10-1',
    dateNextFollowup: '2024-10-1',
    createTime: '2024-10-1',
    status: 1,
    operation: ':',
  },
  {
    id: 5,
    name: '重光',
    phone: '123456789',
    waiter: '黑云压城城欲摧,甲光向日金鳞开',
    intention: '问君能有几多愁？恰似一江春水向东流',
    customerCognitiveApproach: '开宝',
    lastContactTime: '2024-10-1',
    dateNextFollowup: '2024-10-1',
    createTime: '2024-10-1',
    status: 1,
    operation: ':',
  },
  {
    id: 6,
    name: '重光',
    phone: '123456789',
    waiter: '黑云压城城欲摧,甲光向日金鳞开',
    intention: '问君能有几多愁？恰似一江春水向东流',
    customerCognitiveApproach: '开宝',
    lastContactTime: '2024-10-1',
    dateNextFollowup: '2024-10-1',
    createTime: '2024-10-1',
    status: 1,
    operation: ':',
  },
  {
    id: 7,
    name: '重光',
    phone: '123456789',
    waiter: '黑云压城城欲摧,甲光向日金鳞开',
    intention: '问君能有几多愁？恰似一江春水向东流',
    customerCognitiveApproach: '开宝',
    lastContactTime: '2024-10-1',
    dateNextFollowup: '2024-10-1',
    createTime: '2024-10-1',
    status: 1,
    operation: ':',
  },
  {
    id: 8,
    name: '重光',
    phone: '123456789',
    waiter: '黑云压城城欲摧,甲光向日金鳞开',
    intention: '问君能有几多愁？恰似一江春水向东流',
    customerCognitiveApproach: '开宝',
    lastContactTime: '2024-10-1',
    dateNextFollowup: '2024-10-1',
    createTime: '2024-10-1',
    status: 1,
    operation: ':',
  },
  {
    id: 9,
    name: '重光',
    phone: '123456789',
    waiter: '黑云压城城欲摧,甲光向日金鳞开',
    intention: '问君能有几多愁？恰似一江春水向东流',
    customerCognitiveApproach: '开宝',
    lastContactTime: '2024-10-1',
    dateNextFollowup: '2024-10-1',
    createTime: '2024-10-1',
    status: 1,
    operation: ':',
  },
  {
    id: 10,
    name: '重光',
    phone: '123456789',
    waiter: '黑云压城城欲摧,甲光向日金鳞开',
    intention: '问君能有几多愁？恰似一江春水向东流',
    customerCognitiveApproach: '开宝',
    lastContactTime: '2024-10-1',
    dateNextFollowup: '2024-10-1',
    createTime: '2024-10-1',
    status: 1,
    operation: ':',
  },
  {
    id: 11,
    name: '重光',
    phone: '123456789',
    waiter: '黑云压城城欲摧,甲光向日金鳞开',
    intention: '问君能有几多愁？恰似一江春水向东流',
    customerCognitiveApproach: '开宝',
    lastContactTime: '2024-10-1',
    dateNextFollowup: '2024-10-1',
    createTime: '2024-10-1',
    status: 1,
    operation: ':',
  },
  {
    id: 12,
    name: '重光',
    phone: '123456789',
    waiter: '黑云压城城欲摧,甲光向日金鳞开',
    intention: '问君能有几多愁？恰似一江春水向东流',
    customerCognitiveApproach: '开宝',
    lastContactTime: '2024-10-1',
    dateNextFollowup: '2024-10-1',
    createTime: '2024-10-1',
    status: 1,
    operation: ':',
  },
  {
    id: 13,
    name: '重光',
    phone: '123456789',
    waiter: '黑云压城城欲摧,甲光向日金鳞开',
    intention: '问君能有几多愁？恰似一江春水向东流',
    customerCognitiveApproach: '开宝',
    lastContactTime: '2024-10-1',
    dateNextFollowup: '2024-10-1',
    createTime: '2024-10-1',
    status: 1,
    operation: ':',
  },
  {
    id: 14,
    name: '重光',
    phone: '123456789',
    waiter: '黑云压城城欲摧,甲光向日金鳞开',
    intention: '问君能有几多愁？恰似一江春水向东流',
    customerCognitiveApproach: '开宝',
    lastContactTime: '2024-10-1',
    dateNextFollowup: '2024-10-1',
    createTime: '2024-10-1',
    status: 1,
    operation: ':',
  },
  {
    id: 15,
    name: '重光',
    phone: '123456789',
    waiter: '黑云压城城欲摧,甲光向日金鳞开',
    intention: '问君能有几多愁？恰似一江春水向东流',
    customerCognitiveApproach: '开宝',
    lastContactTime: '2024-10-1',
    dateNextFollowup: '2024-10-1',
    createTime: '2024-10-1',
    status: 1,
    operation: ':',
  },
]);
export const columns = ref([
  {
    title: '序号',
    dataIndex: 'id',
    key: 'id',
  },
  {
    title: '姓名',
    dataIndex: 'name',
    key: 'name',
  },
  {
    title: '电话',
    dataIndex: 'phone',
    key: 'phone',
  },
  {
    title: '时代环境',
    dataIndex: 'waiter',
    key: 'waiter',
  },
  {
    title: '脍炙人口',
    dataIndex: 'intention',
    key: 'intention',
  },
  {
    title: '活跃年号',
    dataIndex: 'customerCognitiveApproach',
    key: 'customerCognitiveApproach',
  },
  {
    title: '最近一次联系时间',
    dataIndex: 'lastContactTime',
    key: 'lastContactTime',
  },
  {
    title: '下次跟进时间',
    dataIndex: 'dateNextFollowup',
    key: 'dateNextFollowup',
  },
  {
    title: '创建日期',
    dataIndex: 'createTime',
    key: 'createTime',
  },
  {
    title: '状态',
    dataIndex: 'status',
    key: 'status',
  },
  {
    title: '操作',
    dataIndex: 'operation',
    key: 'operation',
  },
]);
